### ISSUE TITLE
Не запускается 

### ISSUE THREAD

**Issue by Dima353** [Pojirianets/Pokemon-HG-Ru-translation-hack#1]
Не запускается на TWL++ последней версии, это нормально? На какой прошивке работает?

**Comment by Pojirianets** [comment]
Уже известно, что смена файла arm9 в роме на оригинальный позволяет запустить ром на DS.
В ближайшее время в дополнение к существующей версии выпущу дополнительную, с замененным arm9

(Обновление)
Загрузил версию с замененным arm9, можно подтвердить, что запускается на DS?

**Comment by Dima353** [comment]
Спасибо, проверю через несколько часов.

UDP
Все работает, обе версии, на R4 + TWL++, а также на DSi с такой же прошивкой
